NumPy (or Numpy) is a Linear Algebra Library for Python, the reason it is so important for Data Science with Python is that almost all of the libraries in the PyData Ecosystem rely on NumPy as one of their main building blocks.

In [1]:
import numpy as np

Numpy Arrays

NumPy arrays are the main way we will use Numpy. Numpy arrays essentially come in two flavors: vectors and matrices. Vectors are strictly 1-d arrays and matrices are 2-d (but you should note a matrix can still have only one row or one column).

Let's begin our introduction by exploring how to create NumPy arrays.

In [2]:
my_list=[1,2,3]
my_list

[1, 2, 3]

In [3]:
np.array(my_list)

array([1, 2, 3])

In [7]:
my_matrix=[[1,2,3],[4,5,6],[7,8,9]]

In [8]:
my_matrix

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [9]:
np.array(my_matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [10]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [14]:
np.arange(10,50)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

In [16]:
np.arange(30,50)

array([30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46,
       47, 48, 49])

In [17]:
np.arange(2,20,2)

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

In [18]:
np.arange(3,30,3)

array([ 3,  6,  9, 12, 15, 18, 21, 24, 27])

In [19]:
np.arange(5,50,5)

array([ 5, 10, 15, 20, 25, 30, 35, 40, 45])

In [21]:
np.zeros(3)

array([0., 0., 0.])

In [22]:
np.zeros((5,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [23]:
np.zeros((10,10))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [26]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [27]:
np.ones((5,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [28]:
np.ones((10,10))

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [33]:
np.linspace(0,10,3)

array([ 0.,  5., 10.])

In [34]:
np.linspace(0,10)

array([ 0.        ,  0.20408163,  0.40816327,  0.6122449 ,  0.81632653,
        1.02040816,  1.2244898 ,  1.42857143,  1.63265306,  1.83673469,
        2.04081633,  2.24489796,  2.44897959,  2.65306122,  2.85714286,
        3.06122449,  3.26530612,  3.46938776,  3.67346939,  3.87755102,
        4.08163265,  4.28571429,  4.48979592,  4.69387755,  4.89795918,
        5.10204082,  5.30612245,  5.51020408,  5.71428571,  5.91836735,
        6.12244898,  6.32653061,  6.53061224,  6.73469388,  6.93877551,
        7.14285714,  7.34693878,  7.55102041,  7.75510204,  7.95918367,
        8.16326531,  8.36734694,  8.57142857,  8.7755102 ,  8.97959184,
        9.18367347,  9.3877551 ,  9.59183673,  9.79591837, 10.        ])

In [38]:
np.linspace(0,100,6)

array([  0.,  20.,  40.,  60.,  80., 100.])

In [39]:
np.linspace(start = 0, stop = 100, num = 5)

array([  0.,  25.,  50.,  75., 100.])

In [40]:
np.linspace(start=0,stop=10,num=3)


array([ 0.,  5., 10.])

In [42]:
np.eye(8)

array([[1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1.]])

In [43]:
# Python Programming giving an example for
# numpy.eye() method
import numpy as numpy
# 2x2 matrix with 1's on main diagonal
obj1 = numpy.eye(2, dtype = float)
print("Matrix : \n", obj1)
# matrix with Row=2 Column=3 and diagonal=1
obj2 = numpy.eye(2, 3, k = 1)
print("\nMatrix : \n", obj2)

Matrix : 
 [[1. 0.]
 [0. 1.]]

Matrix : 
 [[0. 1. 0.]
 [0. 0. 1.]]


In [46]:
obj1 = numpy.eye(3, dtype = float)

In [47]:
obj1

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [49]:
obj1 = numpy.eye(2, dtype = int)
obj1

array([[1, 0],
       [0, 1]])

In [51]:
obj1 = numpy.eye(6, dtype = float)
obj1

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

In [52]:
np.random.rand(0)

array([], dtype=float64)

In [53]:
np.random.rand(5)

array([0.0269301 , 0.65133096, 0.8198715 , 0.96198428, 0.5454814 ])

In [57]:
np.random.rand(5,10)

array([[0.9776984 , 0.0252904 , 0.90560255, 0.61804846, 0.27725436,
        0.93061828, 0.93547247, 0.64165446, 0.41097117, 0.38206412],
       [0.25743845, 0.44870898, 0.04735131, 0.1043162 , 0.0064728 ,
        0.76721773, 0.62665813, 0.04797779, 0.77124551, 0.55225918],
       [0.36275382, 0.31890167, 0.91708266, 0.38500155, 0.73577487,
        0.34931544, 0.63931024, 0.74871824, 0.96707232, 0.64638454],
       [0.95983252, 0.36303727, 0.51930297, 0.67138332, 0.61007803,
        0.67001725, 0.89684989, 0.06751468, 0.49590183, 0.07923302],
       [0.47223845, 0.75511112, 0.79284152, 0.15890529, 0.62446228,
        0.03140276, 0.39923368, 0.45574735, 0.87416154, 0.15696649]])

In [63]:
np.random.rand(1,5)

array([[0.90189727, 0.11943306, 0.56320877, 0.6472419 , 0.79365439]])

In [64]:
np.random.randn(1,5)

array([[ 0.32894768, -1.20449719,  1.88143007, -0.2348794 ,  0.3051189 ]])

In [66]:
np.random.randint(1,50)

40

In [69]:
arr = np.arange(25)
ranarr = np.random.randint(0,50,10)
arr


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [68]:
ranarr

array([14,  9, 25, 11, 23,  1,  9, 15, 36, 11])

In [70]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [75]:
arr = np.arange(100)


array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [78]:
arr.reshape(10,10)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [79]:
ranarr

array([28, 39, 47, 37, 15, 45, 35, 31, 32, 26])

In [80]:
ranarr.max()

47

In [81]:
ranarr.min()

15

In [83]:
ranarr.std()

8.92468486838611

In [86]:
ranarr.mean()

33.5

In [87]:
ranarr.argmax()

2

In [88]:
ranarr.argmin()

4

In [89]:
arr.shape

(100,)

In [90]:
ranarr.shape

(10,)

In [92]:
arr.reshape(1,100).shape

(1, 100)

In [93]:
arr.reshape(100,1).shape

(100, 1)

In [95]:
arr.reshape(100,1)

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23],
       [24],
       [25],
       [26],
       [27],
       [28],
       [29],
       [30],
       [31],
       [32],
       [33],
       [34],
       [35],
       [36],
       [37],
       [38],
       [39],
       [40],
       [41],
       [42],
       [43],
       [44],
       [45],
       [46],
       [47],
       [48],
       [49],
       [50],
       [51],
       [52],
       [53],
       [54],
       [55],
       [56],
       [57],
       [58],
       [59],
       [60],
       [61],
       [62],
       [63],
       [64],
       [65],
       [66],
       [67],
       [68],
       [69],
       [70],
       [71],
       [72],
       [73],
       [74],
       [75],
       [76],

In [96]:
arr.dtype

dtype('int32')